---
name: Benchmarks

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.13"

permissions:
  contents: read

jobs:
  benchmarks:
    name: CodSpeed
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: 🏗 Set up Poetry
        run: pipx install poetry
      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: 🏗 Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: 🏗 Install Python dependencies
        run: poetry install --no-interaction
      - name: 🚀 Run benchmarks
        uses: CodSpeedHQ/action@c79cfd49571e40b42b172bd0e91eabc0c949d9a7 # v4.13.1
        with:
          run: poetry run pytest tests/benchmarks/ --codspeed --no-cov
          mode: walltime
          token: ${{ secrets.CODSPEED_TOKEN }}
