---
name: CodSpeed

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.13"

permissions:
  contents: read

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # for OpenID Connect authentication with CodSpeed
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: 🏗 Set up Poetry
        run: pipx install poetry
      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: 🏗 Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: 🏗 Install dependencies
        run: poetry install --no-interaction --all-extras
      - name: 🚀 Run benchmarks
        uses: CodSpeedHQ/action@c145068895e045cc725ee76fcd2307624b65c3af # v4.17.5
        with:
          mode: simulation
          run: poetry run pytest tests/ --codspeed --no-cov
